### ISSUE TITLE
Beim ersten Start des Plugins gibt es eine FnF-Exception (checkpoints.xml)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hansriezebos/projectusus#1]
```
Error
Fri Nov 20 08:27:02 CET 2009
Unable to load file.

java.io.FileNotFoundException:
D:\Entwicklung\.metadata\.plugins\org.projectusus.core\checkpoints.xml (Das
System kann die angegebene Datei nicht finden)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at org.projectusus.core.internal.XmlLoader.loadElements(XmlLoader.java:49)
at org.projectusus.core.internal.XmlLoader.load(XmlLoader.java:36)
at
org.projectusus.core.internal.proportions.modelupdate.UsusModelHistory.initCheck
points(UsusModelHistory.java:51)
at
org.projectusus.core.internal.proportions.modelupdate.UsusModelHistory.<init>(Us
usModelHistory.java:21)
at
org.projectusus.core.internal.proportions.UsusModel.<init>(UsusModel.java:34)
at
org.projectusus.core.internal.proportions.UsusModel.getUsusModel(UsusModel.java:
40)
at org.projectusus.core.internal.UsusCorePlugin.start(UsusCorePlugin.java:34)
at
org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextIm
pl.java:782)
at java.security.AccessController.doPrivileged(Native Method)
at
org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(Bundle
ContextImpl.java:773)
at
org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextIm
pl.java:754)
at
org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:
352)
at
org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.jav
a:280)
at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:408)
at
org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(
EclipseLazyStarter.java:111)
at
org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathMan
ager.java:449)
at
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultC
lassLoader.java:211)
at
org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:3
76)
at
org.eclipse.osgi.internal.loader.SingleSourcePackage.loadClass(SingleSourcePacka
ge.java:33)
at
org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.jav
a:449)
at
org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:405)
at
org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:393)
at
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassL
oader.java:105)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClassInternal(Unknown Source)
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at
org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExt
ension(RegistryStrategyOSGI.java:170)
at
org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(E
xtensionRegistry.java:874)
at
org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtensio
n(ConfigurationElement.java:243)
at
org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableEx
tension(ConfigurationElementHandle.java:51)
at
org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:259
)
at
org.eclipse.ui.internal.registry.ViewDescriptor.createView(ViewDescriptor.java:6
3)
at
org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:324)
at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:226)
at
org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.ja
va:595)
at org.eclipse.ui.internal.PartPane.setVisible(PartPane.java:313)
at org.eclipse.ui.internal.ViewPane.setVisible(ViewPane.java:529)
at
org.eclipse.ui.internal.presentations.PresentablePart.setVisible(PresentablePart
.java:180)
at
org.eclipse.ui.internal.presentations.util.PresentablePartFolder.select(Presenta
blePartFolder.java:270)
at
org.eclipse.ui.internal.presentations.util.LeftToRightTabOrder.select(LeftToRigh
tTabOrder.java:65)
at
org.eclipse.ui.internal.presentations.util.TabbedStackPresentation.selectPart(Ta
bbedStackPresentation.java:473)
at
org.eclipse.ui.internal.PartStack.refreshPresentationSelection(PartStack.java:12
56)
at org.eclipse.ui.internal.PartStack.setSelection(PartStack.java:1209)
at org.eclipse.ui.internal.PartStack.showPart(PartStack.java:1608)
at org.eclipse.ui.internal.PartStack.createControl(PartStack.java:649)
at org.eclipse.ui.internal.PartStack.createControl(PartStack.java:576)
at
org.eclipse.ui.internal.PartSashContainer.createControl(PartSashContainer.java:5
68)
at
org.eclipse.ui.internal.PerspectiveHelper.activate(PerspectiveHelper.java:272)
at org.eclipse.ui.internal.Perspective.onActivate(Perspective.java:981)
at
org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3608)
at
org.eclipse.ui.internal.WorkbenchPage.busySetPerspective(WorkbenchPage.java:1037
)
at org.eclipse.ui.internal.WorkbenchPage.access$16(WorkbenchPage.java:1021)
at org.eclipse.ui.internal.WorkbenchPage$19.run(WorkbenchPage.java:3709)
at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
at
org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:3707)
at
org.eclipse.ui.handlers.ShowPerspectiveHandler.openPerspective(ShowPerspectiveHa
ndler.java:152)
at
org.eclipse.ui.handlers.ShowPerspectiveHandler.openOther(ShowPerspectiveHandler.
java:124)
at
org.eclipse.ui.handlers.ShowPerspectiveHandler.execute(ShowPerspectiveHandler.ja
va:63)
at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
at org.eclipse.core.commands.Command.executeWithChecks(Command.java:476)
at
org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.ja
va:178)
at
org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandler
Service.java:247)
at org.eclipse.ui.actions.PerspectiveMenu.runOther(PerspectiveMenu.java:376)
at
org.eclipse.ui.actions.PerspectiveMenu$3.runWithEvent(PerspectiveMenu.java:130)
at
org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionCont
ributionItem.java:584)
at
org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.
java:501)
at
org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContribution
Item.java:411)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1003)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3880)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3473)
at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java
:113)
at
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ecli
pseAppLauncher.java:110)
at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLau
ncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:559)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:514)
at org.eclipse.equinox.launcher.Main.run(Main.java:1311)

```

Original issue reported on code.google.com by `nicol...@gmx.de` on 20 Nov 2009 at 12:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `nicol...@gmx.de` on 20 Nov 2009 at 12:49
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in HEAD.

This was only a log entry, there was no functionality impeded. (I've removed 
the log
in case the file didn't exist, which is normally the case with a first-install 
:-)
```

Original comment by `leiffren...@googlemail.com` on 21 Nov 2009 at 1:48
- Changed state: **Fixed**
