### ISSUE TITLE
BackingStoreException beim Canceln eines proportions computers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hansriezebos/projectusus#2]
```
Startet man einen proportion computer run und startet während des Laufs ein
weiterer run (z. B. weil man ein weiteres Projekt in der supported-Liste
ausgewählt hat), wird ein Fenster angezeigt, in dem man den zweiten Run
abbrechen kann. Bricht man ihn ab (durch Klicken auf den roten Kasten),
gibt es diese Exception:

Error
Fri Nov 20 08:55:42 CET 2009
Operation canceled.

org.osgi.service.prefs.BackingStoreException: Operation canceled.
at
org.eclipse.core.internal.resources.ProjectPreferences.save(ProjectPreferences.j
ava:588)
at
org.eclipse.core.internal.preferences.EclipsePreferences.flush(EclipsePreference
s.java:352)
at
org.eclipse.core.internal.resources.ProjectPreferences.flush(ProjectPreferences.
java:383)
at
org.projectusus.core.internal.project.UsusProject.setUsusProject(UsusProject.jav
a:37)
at
org.projectusus.ui.internal.coveredprojects.CoveredProjectsView.updateUsusProjec
t(CoveredProjectsView.java:76)
at
org.projectusus.ui.internal.coveredprojects.CoveredProjectsView.access$0(Covered
ProjectsView.java:69)
at
org.projectusus.ui.internal.coveredprojects.CoveredProjectsView$1.checkStateChan
ged(CoveredProjectsView.java:63)
at
org.eclipse.jface.viewers.CheckboxTableViewer$1.run(CheckboxTableViewer.java:212
)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.runtime.Platform.run(Platform.java:888)
at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:48)
at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
at
org.eclipse.jface.viewers.CheckboxTableViewer.fireCheckStateChanged(CheckboxTabl
eViewer.java:210)
at
org.eclipse.jface.viewers.CheckboxTableViewer.handleSelect(CheckboxTableViewer.j
ava:300)
at
org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.jav
a:1190)
at
org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:228)
at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:222)
at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:389)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1003)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3880)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3473)
at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
at
org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java
:113)
at
org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Ecli
pseAppLauncher.java:110)
at
org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLau
ncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:559)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:514)
at org.eclipse.equinox.launcher.Main.run(Main.java:1311)


```

Original issue reported on code.google.com by `nicol...@gmx.de` on 20 Nov 2009 at 12:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `nicol...@gmx.de` on 20 Nov 2009 at 12:49
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The exception arises from the call to flush() on the project preferences node 
during
setUsusProject(). (I.e. it has only to do with how we persist the setting that a
project is a Usus project, it has no relation to the code proportions computer.)

It's only a log entry, the code actually works correctly.

Trouble is that we cannot determine by the exception type whether the exception 
was
thrown because of a valid user operation (i.e. cancel) or whether there was an 
actual
file operation error. To cover the latter case, we have to log it; 
unfortunately that
means we also get these log entries in cases where it was just a cancel.
```

Original comment by `leiffren...@googlemail.com` on 21 Nov 2009 at 12:00
- Changed state: **WontFix**
