### ISSUE TITLE
NullPointerException when computing code proportions for the first time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hansriezebos/projectusus#22]
```
java.lang.NullPointerException
at 
org.projectusus.core.internal.proportions.rawdata.FileRawData.addClassReference
(FileRawData.java:140)
at 
org.projectusus.core.internal.proportions.rawdata.collectors.ACDCollector.visit
(ACDCollector.java:62)
at 
org.projectusus.core.internal.proportions.rawdata.collectors.ACDCollector.visit
(ACDCollector.java:48)
at org.eclipse.jdt.core.dom.ArrayType.accept0(ArrayType.java:139)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2478)
at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2525)
at 
org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:496)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2478)
at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2548)
at 
org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:484)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2478)
at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2548)
at 
org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:214)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2478)
at 
org.projectusus.core.internal.proportions.rawdata.jdtdriver.FileDriver.compute
(FileDriver.java:35)
at 
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.runDriverO
nFile
(JDTDriver.java:69)
at 
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.runDriver
(JDTDriver.java:63)
at 
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.runInterna
l
(JDTDriver.java:54)
at 
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.run
(JDTDriver.java:37)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.computeJavaCodeMetrics
(CodeProportionsComputerJob.java:96)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.performComputation
(CodeProportionsComputerJob.java:84)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.performRun
(CodeProportionsComputerJob.java:63)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.run
(CodeProportionsComputerJob.java:56)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Original issue reported on code.google.com by `mphilipp82@gmail.com` on 28 Jan 2010 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
Anscheinend ist das referencedElement null, weil der Ordner explizit vom Build 
Path 
ausgeschlossen wurde. Java-Klassen, die nicht im Build Path enthalten sind, 
sollten 
vermutlich gar nicht erst besucht werden.
```

Original comment by `mphilipp82@gmail.com` on 28 Jan 2010 at 10:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `leiffren...@googlemail.com` on 28 Jan 2010 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r385.
```

Original comment by `mphilipp82@gmail.com` on 30 Jan 2010 at 2:17
- Changed state: **Fixed**
