### ISSUE TITLE
ConcurrentModificationException while refreshing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hansriezebos/projectusus#23]
```
What steps will reproduce the problem?
1. Add Projects to USUS Projects
2. Refresh


What is the expected output? What do you see instead?

Exception Occurs

java.util.ConcurrentModificationException
at java.util.Hashtable$Enumerator.next(Hashtable.java:1031)
at 
org.projectusus.core.internal.proportions.rawdata.WorkspaceRawData.dropAllR
awData(WorkspaceRawData.java:52)
at 
org.projectusus.core.internal.proportions.rawdata.UsusModel.dropAllRawData
(UsusModel.java:60)
at 
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.run
(JDTDriver.java:29)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsC
omputerJob.computeJavaCodeMetrics(CodeProportionsComputerJob.java:90)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsC
omputerJob.performComputation(CodeProportionsComputerJob.java:78)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsC
omputerJob.performRun(CodeProportionsComputerJob.java:62)
at 
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsC
omputerJob.run(CodeProportionsComputerJob.java:55)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Original issue reported on code.google.com by `s.w.schu...@googlemail.com` on 1 Mar 2010 at 9:03

**Comment by GoogleCodeExporter** [comment]
Original comment by `s.w.schu...@googlemail.com` on 1 Mar 2010 at 9:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `leiffren...@googlemail.com` on 1 Mar 2010 at 6:38

**Comment by GoogleCodeExporter** [comment]
```
Problem was dropAllRawData by itself, looping over a keySet of a HashTable while
removing each element...
```

Original comment by `David.Bu...@gmx.de` on 7 Mar 2010 at 9:25
- Changed state: **Fixed**
