### ISSUE TITLE
NPE in code proportions computer with unresolved compile dependencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hansriezebos/projectusus#24]
```
What steps will reproduce the problem?

- create a plug-in project 'a'
- create a plug-in project 'b'
- make 'a' dependent on 'b'
- rename b's Activator to Bctivator and make a reference from Activator to
Bctivator

=> error dialog and message in the log:

Error
Sat May 08 19:19:22 CEST 2010
Errors occurred during code proportions computation.

Error
Sat May 08 19:19:22 CEST 2010
[No details.]

java.lang.NullPointerException
    at
org.projectusus.core.internal.proportions.rawdata.collectors.ACDCollector.visit(
ACDCollector.java:60)
    at org.eclipse.jdt.core.dom.SimpleType.accept0(SimpleType.java:135)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2480)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2528)
    at
org.eclipse.jdt.core.dom.VariableDeclarationStatement.accept0(VariableDeclaratio
nStatement.java:272)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2480)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2551)
    at org.eclipse.jdt.core.dom.Block.accept0(Block.java:136)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2480)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2528)
    at
org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:502)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2480)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2551)
    at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:484)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2480)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2551)
    at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:219)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2480)
    at
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JavaFileDriver.compu
te(JavaFileDriver.java:34)
    at
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.runDriverO
nFile(JDTDriver.java:73)
    at
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.runDriver(
JDTDriver.java:67)
    at
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.computeCha
ngedFiles(JDTDriver.java:57)
    at
org.projectusus.core.internal.proportions.rawdata.jdtdriver.JDTDriver.run(JDTDri
ver.java:40)
    at
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.computeJavaCodeMetrics(CodeProportionsComputerJob.java:63)
    at
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.performRun(CodeProportionsComputerJob.java:48)
    at
org.projectusus.core.internal.proportions.modelcomputation.CodeProportionsComput
erJob.run(CodeProportionsComputerJob.java:41)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)





```

Original issue reported on code.google.com by `leiffren...@googlemail.com` on 8 May 2010 at 5:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `leiffren...@googlemail.com` on 8 May 2010 at 5:25
- Added labels: **Priority-Critical**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
I think it's generally a problem with compilation errors that stem from 
unresolved
types; can be reproduced more easily:
- new Java project, new class
- make Usus project
- write: List<Object> list;
- List is still unresolved (no import, and organize imports can't decide which 
list
it is) -> compile error -> Usus error message box
```

Original comment by `leiffren...@googlemail.com` on 8 May 2010 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the bug report! This was a stupid issue that I introduced when 
trying to resolve some type 
occurrence. It is fixed in the HEAD. I will release a plugin including the fix 
today.
```

Original comment by `nicol...@gmx.de` on 9 May 2010 at 7:25
- Changed state: **Fixed**
