### ISSUE TITLE
ConcurrentModificationException beim Speichern eines veränderten Files während einer Berechnung

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hansriezebos/projectusus#3]
```
Speichert man ein verändertes File, während eine Berechnung läuft, gibt es
 eine ConcurrentModificationException:

java.util.ConcurrentModificationException
at java.util.Hashtable$Enumerator.next(Unknown Source)
at
org.projectusus.core.internal.proportions.sqi.RawData.getViolationCount(RawData.
java:35)
at
org.projectusus.core.internal.proportions.sqi.WorkspaceRawData.getCodeProportion
(WorkspaceRawData.java:62)
at
org.projectusus.core.internal.proportions.CodeProportionsComputerJob.computeJava
CodeMetrics(CodeProportionsComputerJob.java:88)
at
org.projectusus.core.internal.proportions.CodeProportionsComputerJob.performComp
utation(CodeProportionsComputerJob.java:72)
at
org.projectusus.core.internal.proportions.CodeProportionsComputerJob.performRun(
CodeProportionsComputerJob.java:61)
at
org.projectusus.core.internal.proportions.CodeProportionsComputerJob.run(CodePro
portionsComputerJob.java:54)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) 
```

Original issue reported on code.google.com by `nicol...@gmx.de` on 20 Nov 2009 at 12:48

**Comment by GoogleCodeExporter** [comment]
Original comment by `nicol...@gmx.de` on 20 Nov 2009 at 12:49
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
All methods on RawData are now synchronized.
```

Original comment by `nicol...@gmx.de` on 23 Nov 2009 at 1:11
- Changed state: **Fixed**
